import OAIHighPrincipalProduct
import OAIHighRamifiedBound
import OAIHighHolomorphic
import OAIHighGlobalCorrection
import OAIHighSlotEstimate
import OAIHighFiniteProductBounds
import OAIHighFiniteProductX
import OAIHighFixedSource
import OAIHighFiniteProductWZ
import OAIHighSourceWZ
import OAIHighComplexSlotBounds
import OAIHighSourceContours
import OAIHighArithmeticLines
import OAIHighOrderedContours
import OAIHighResidueBounds
import OAIHighOuterContours
import OAIHighUniformTails
import OAIHighHighSlices
import OAIHighResidueMoments
import OAIHighXTransport
import OAIHighZTransport
import OAIHighTripleTransport
import OAIHighInitialPlacement
import OAIHighSelectedTerms
import OAIHighSelectedError
import OAIHighSelectedUnramified
import OAIHighSelectedBound
import OAIHighSelectedRamified
import OAIHighSelectedActual
import OAIHighSelectedLocal
import OAIHighSelectedSlotSums
import OAIHighWGrowth
import OAIHighNonprincipalShift
import OAIHighTupleSums
import OAIHighTupleBound
import OAIHighPhysicalTuple
import OAIHighDyadBound
import OAIHighDyadIntegral
import OAIHighFixedIntegral
import OAIHighWZTransport
import OAIHighSourceTransport
import OAIHighPhysicalDyad
import OAIHighTailScales
import OAIHighSmallDyad
import OAIHighSmallTail
import OAIHighLargeDyad
import OAIHighLargeTail
import OAIHighLargeSaving
import OAIHighCentralCrude
import OAIHighCentralFiniteError
import OAIHighCentralExponent
import OAIHighCentralSlotExponent
import OAIHighCentralClassArithmetic
import OAIHighCentralBatch
import OAIHighCentralAmplitudeBatch
import OAIHighCentralClassMoments
import OAIHighCentralArithmetic
import OAIHighCentralIntegral
import OAIHighCentralNormalizer
import OAIHighCentralNormalized
import OAIHighCentralCollected
import OAIHighSlotLengths
import OAIHighCentralBudget
import OAIHighData
import OAIHighFloorArithmetic
import OAIHighFloorGlobal
import OAIHighFloorIntegral
import OAIHighFloorNormalized
import OAIHighFloorSaving
import OAIHighFloorCollected
import OAIHighPhysicalSmallTail
import OAIHighPhysicalLargeTail
import OAIHighCanonicalTails
import OAIHighCanonicalReduction
import OAIHighCubeCrude
import OAIHighCubeFiniteError
import OAIHighCanonicalCubeReduction
import OAIHighCanonicalCubeChoice
import OAIHighCanonicalRayCube
import OAIHighSignalShift
import OAIHighPrincipalRatio
import OAIHighPrincipalResidue
import OAIHighPrincipalNormalizedIdentity
import OAIHighPrincipalActualBound
import OAIHighPrincipalScale
import OAIHighPrincipalRemainder
import OAIHighPrincipalPhysicalRemainder
import OAIHighPrincipalWindow
import OAIHighPrincipalSharp
import OAIHighPrincipalPointwise
import OAIHighPrincipalUniform
import OAIHighPrincipalOrdered
import OAIHighPrincipalLowRemainder
import OAIHighPrincipalPool
import OAIHighPrincipalPhysicalLow
import OAIHighPrincipalNormalized
import OAIHighNormalizedTransport
import OAIHighNormalizedTransportSaving
import OAIHighNonfloorTransport
import OAIHighDetectorBeta
import OAIHighFromMoments
import OAIHighAssemblyData
import OAIHighAssemblyMomentInput
import OAIHighAssemblyClass
import OAIHighAssemblyArithmetic
import OAIHighAssemblyIntegral
import OAIHighAssemblyNormalized
import OAIHighAssemblyCollected
import OAIHighAssemblyHigh
import OAIHighAssemblyFixedHigh
import OAIHighSignalIdentity
import OAIHighCommonProbe
import OAIHighAssemblyFinal
import OAIHighMomentEnergy

#print axioms PerturbedZeroFreeBound.exists_perturbed_principal_correction
#print axioms OAI.SevenEighths.ProbeEuler.bound_ramified_closed_on_perturbed_region
#print axioms OAI.SevenEighths.ProbeEuler.ramified_closed_analytic_z_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePhysical.exists_perturbed_global_correction
#print axioms OAI.SevenEighths.ProbePhysical.bound_global_closed_correction_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePhysical.global_closed_correction_analytic_z_on_perturbed_region
#print axioms OAI.SevenEighths.PrincipalSlotEstimate.bound_weighted_region_slots_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.bound_combined_slots_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductX.continued_source_differentiable_strip_on_perturbed_boundary
#print axioms OAI.SevenEighths.Parameters.exists_fixed_source_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.combined_slot_analytic_z_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.source_multiplier_differentiable_z_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.bound_combined_slots_with_complex_weight_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.source_residue_z_shift_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.source_ordered_ae_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.source_initial_ordered_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.source_uniform_joint_tails_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.raw_source_uniform_high_slices_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.residue_uniform_tails_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalTransport.source_initial_ordered_at_a_on_perturbed_region
#print axioms OAI.SevenEighths.ProbeEuler.sourceRowTerm_selected_base_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.continued_selected_slot_bound_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.calibrated_physicalRow_w_growth_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.nonprincipal_w_integral_eq_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.continued_selected_tuple_with_correction_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.calibrated_physical_row_dyad_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.rowIntegral_source_lines_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.small_physical_dyads_sum_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.large_physical_dyad_bound_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.large_physical_tail_arbitrary_saving_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.finite_rectangle_arbitrary_saving_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.balanced_mixed_saving_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_slot_product
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_class_cube_arithmetic
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_source_amplitude_batches
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_nonfloor_class_from_raw_moments
#print axioms OAI.SevenEighths.ProbeHighRowFamily.balanced_adaptive_saving_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_nonfloor_cube_arithmetic
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_nonfloor_cube_norm
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_ray_normalizer_inverse
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_normalized_nonfloor_cube
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_nonfloor_rows_saving
#print axioms OAI.SevenEighths.Parameters.exists_physical_slot_lengths_with_mass
#print axioms OAI.SevenEighths.Parameters.exists_perturbed_central_budget
#print axioms OAI.SevenEighths.Parameters.exists_perturbed_high_data
#print axioms OAI.SevenEighths.Parameters.exists_perturbed_high_data_fine
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_floor_cube_arithmetic
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_global_floor_cube_arithmetic
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_global_floor_cube_norm
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_normalized_floor_cube
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_floor_cube_saving
#print axioms OAI.SevenEighths.ProbeHighRowFamily.perturbed_floor_rows_saving
#print axioms OAI.SevenEighths.ProbeHighRowFamily.small_perturbed_physical_tail
#print axioms OAI.SevenEighths.ProbeHighRowFamily.large_perturbed_physical_tail
#print axioms OAI.SevenEighths.ProbeHighRowFamily.canonical_small_perturbed_tail
#print axioms OAI.SevenEighths.ProbeHighRowFamily.canonical_large_perturbed_tail
#print axioms OAI.SevenEighths.ProbeHighRowFamily.canonical_probe_minus_perturbed_central
#print axioms OAI.SevenEighths.ProbeHighRowFamily.original_row_cube_arbitrary_saving_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.finite_cube_arbitrary_saving_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.canonical_probe_minus_perturbed_cube
#print axioms OAI.SevenEighths.ProbeHighRowFamily.canonical_probe_exists_perturbed_cube
#print axioms OAI.SevenEighths.ProbeHighRowFamily.canonical_probe_exists_perturbed_ray_cube
#print axioms OAI.SevenEighths.HeckeSignalShift.contour_shift_left_on_perturbed_boundary
#print axioms OAI.SevenEighths.PrincipalSignalComparison.slotRatio_error_on_perturbed_boundary
#print axioms OAI.SevenEighths.PrincipalSignalComparison.slotResidue_bound_of_reciprocal_bound_on_perturbed_boundary
#print axioms OAI.SevenEighths.PrincipalSignalComparison.sourceResidueIntegral_normalized_with_perturbed_lengths
#print axioms OAI.SevenEighths.PrincipalSignalComparison.exists_normalized_actual_source_bound_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbePrincipalRemainderBounds.perturbed_source_scale_identity
#print axioms OAI.SevenEighths.ProbePrincipalRemainderBounds.source_remainders_fixed_contour_saving
#print axioms OAI.SevenEighths.ProbePrincipalPhysical.physical_principal_residue_remainder_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbePrincipalRemainderBounds.ordered_remainders_scale_bound_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbePrincipalNormalized.actual_ray_principal_comparison_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.actual_normalized_probe_transport_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.actual_normalized_probe_transport_saving_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.actual_nonfloor_probe_transport_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.detectorMaximum_le_beta
#print axioms OAI.SevenEighths.ProbeHighRowFamily.actual_high_probe_from_raw_moments_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFinalAssembly.exists_perturbed_source_data
#print axioms OAI.SevenEighths.ProbeFinalAssembly.PerturbedSourceData.probe_low
#print axioms OAI.SevenEighths.ProbeFinalAssembly.chosen_perturbed_input_of_raw
#print axioms OAI.SevenEighths.ProbeFinalAssembly.chosen_perturbed_input_of_fine
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_chosen_data_height
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_nonfloor_class_from_count_parameters
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_nonfloor_cube_arithmetic_with_count_parameters
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_nonfloor_cube_norm_with_count_parameters
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_normalized_nonfloor_cube_with_count_parameters
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_nonfloor_rows_saving_with_count_parameters
#print axioms OAI.SevenEighths.ProbeFinalAssembly.actual_high_probe_from_count_moments_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFinalAssembly.fixed_perturbed_high_bound
#print axioms OAI.SevenEighths.HeckeSignal.nonzero_of_perturbed_probe_bounds
#print axioms OAI.SevenEighths.HeckeCommonProbe.beta_le_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFinalAssembly.common_perturbed_probe_of_chosen_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.beta_le_perturbed_boundary_of_chosen_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.beta_le_perturbed_boundary_of_fine_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.hecke_of_chosen_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.dirichlet_of_chosen_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.zeta_of_chosen_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.common_perturbed_probe_of_raw_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.beta_le_perturbed_boundary_of_raw_and_chosen_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.hecke_of_raw_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.dirichlet_of_raw_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.zeta_of_raw_perturbed_moments
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_detector_certified_band
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbedFixedIdeal_ne_zero
#print axioms OAI.SevenEighths.ProbeFinalAssembly.perturbed_plain_inputs
