import OAIHighPrincipalProduct
import OAIHighRamifiedBound
import OAIHighHolomorphic
import OAIHighGlobalCorrection
import OAIHighSlotEstimate
import OAIHighFiniteProductBounds
import OAIHighFiniteProductX
import OAIHighFixedSource
import OAIHighFiniteProductWZ
import OAIHighSourceWZ
import OAIHighComplexSlotBounds
import OAIHighSourceContours
import OAIHighArithmeticLines
import OAIHighOrderedContours
import OAIHighResidueBounds
import OAIHighOuterContours
import OAIHighUniformTails
import OAIHighHighSlices
import OAIHighResidueMoments
import OAIHighXTransport
import OAIHighZTransport
import OAIHighTripleTransport
import OAIHighInitialPlacement
import OAIHighSelectedTerms
import OAIHighSelectedError
import OAIHighSelectedUnramified
import OAIHighSelectedBound
import OAIHighSelectedRamified
import OAIHighSelectedActual
import OAIHighSelectedLocal
import OAIHighSelectedSlotSums
import OAIHighWGrowth
import OAIHighNonprincipalShift
import OAIHighTupleSums
import OAIHighTupleBound
import OAIHighPhysicalTuple
import OAIHighDyadBound
import OAIHighDyadIntegral
import OAIHighFixedIntegral
import OAIHighWZTransport
import OAIHighSourceTransport
import OAIHighPhysicalDyad
import OAIHighTailScales
import OAIHighSmallDyad
import OAIHighSmallTail
import OAIHighLargeDyad
import OAIHighLargeTail
import OAIHighLargeSaving

#print axioms PerturbedZeroFreeBound.exists_perturbed_principal_correction
#print axioms OAI.SevenEighths.ProbeEuler.bound_ramified_closed_on_perturbed_region
#print axioms OAI.SevenEighths.ProbeEuler.ramified_closed_analytic_z_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePhysical.exists_perturbed_global_correction
#print axioms OAI.SevenEighths.ProbePhysical.bound_global_closed_correction_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePhysical.global_closed_correction_analytic_z_on_perturbed_region
#print axioms OAI.SevenEighths.PrincipalSlotEstimate.bound_weighted_region_slots_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.bound_combined_slots_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductX.continued_source_differentiable_strip_on_perturbed_boundary
#print axioms OAI.SevenEighths.Parameters.exists_fixed_source_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.combined_slot_analytic_z_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.source_multiplier_differentiable_z_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.bound_combined_slots_with_complex_weight_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeFiniteProductBounds.source_residue_z_shift_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.source_ordered_ae_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.source_initial_ordered_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.source_uniform_joint_tails_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.raw_source_uniform_high_slices_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalContours.residue_uniform_tails_on_perturbed_region
#print axioms OAI.SevenEighths.ProbePrincipalTransport.source_initial_ordered_at_a_on_perturbed_region
#print axioms OAI.SevenEighths.ProbeEuler.sourceRowTerm_selected_base_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.continued_selected_slot_bound_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.calibrated_physicalRow_w_growth_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.nonprincipal_w_integral_eq_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.continued_selected_tuple_with_correction_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.calibrated_physical_row_dyad_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.rowIntegral_source_lines_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.small_physical_dyads_sum_on_perturbed_boundary
#print axioms OAI.SevenEighths.ProbeHighRowFamily.large_physical_dyad_bound_with_perturbed_lengths
#print axioms OAI.SevenEighths.ProbeHighRowFamily.large_physical_tail_arbitrary_saving_with_perturbed_lengths
